language: python
python:
  - "2.7"
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install flake8
  - python setup.py install
  - pip install -r devRequirements.txt
# command to run tests
script: nosetests ddsc
before_script:
  - flake8 --ignore E501 ddsc/
