language: python
python:
  - "2.7"
  - "3.5"
# command to install dependencies
install: 
  - "python setup.py install"
  - "pip install -r devRequirements.txt"
# command to run tests
script: nosetests ddsc
