language: python
python:
  - "2.7"
  - "3.5"
# command to run tests
script: nosetests ddsc
install:
  - pip install -r requirements.txt
  - pip install flake8
before_script:
  - flake8 --ignore E501 ddsc/
