
class RetrySettings(object):
    SEND_EXTERNAL_PUT_RETRY_TIMES = 5
    SEND_EXTERNAL_RETRY_SECONDS = 20
    SEND_EXTERNAL_FORBIDDEN_RETRY_TIMES = 2
    RESOURCE_NOT_CONSISTENT_RETRY_SECONDS = 2
    FETCH_EXTERNAL_PUT_RETRY_TIMES = 5
    FETCH_EXTERNAL_RETRY_SECONDS = 20
    SERVICE_DOWN_RETRY_SECONDS = 60
    CONNECTION_RETRY_TIMES = 5
    CONNECTION_RETRY_SECONDS = 1
